/**
 * Domain models exposed by the DAL. These are data-source-agnostic — the app
 * consumes these shapes regardless of whether the backing source is REST,
 * GraphQL, localStorage, or local JSON.
 */

/** Lightweight catalogue entry — drives the sidebar/catalogue list. */
export interface ApiSummary {
  id: string
  name: string
  version: string
  baseUrl: string
  description?: string
}

/** SDK / library link for an API, loaded from config (not hardcoded in JSX). */
export interface SdkLink {
  lang: string
  install: string
  repo: string
}

/** Full per-API metadata (catalogue entry + SDK links). */
export interface ApiDetail extends ApiSummary {
  sdks: SdkLink[]
}

/** One entry in an API's error reference catalogue. */
export interface ErrorRefEntry {
  /** App-level or HTTP code, e.g. "RATE_LIMITED" or "404". */
  code: string
  httpStatus?: number
  title: string
  description: string
  resolution?: string
}

/**
 * Tier-2 cross-API search hit: which API contains the keyword. Deliberately
 * id-agnostic — endpoint anchor ids are a frontend concern (generated by the
 * spec parser), so the DAL never returns them. The frontend resolves the exact
 * matching endpoints against its cached parse (see `useGlobalSearch`).
 */
export interface ApiSearchHit {
  apiId: string
  apiName: string
}
