/**
 * Domain models exposed by the DAL. These are data-source-agnostic — the app
 * consumes these shapes regardless of whether the backing source is REST,
 * GraphQL, localStorage, or local JSON.
 */

/** Lightweight catalogue entry — drives the sidebar/catalogue list. */
export interface ApiSummary {
  id: string
  name: string
  version: string
  baseUrl: string
  description?: string
}

/** SDK / library link for an API, loaded from config (not hardcoded in JSX). */
export interface SdkLink {
  lang: string
  install: string
  repo: string
}

/** Full per-API metadata (catalogue entry + SDK links). */
export interface ApiDetail extends ApiSummary {
  sdks: SdkLink[]
}

/** One entry in an API's error reference catalogue. */
export interface ErrorRefEntry {
  /** App-level or HTTP code, e.g. "RATE_LIMITED" or "404". */
  code: string
  httpStatus?: number
  title: string
  description: string
  resolution?: string
}

/**
 * Changelog entry type (§2.7) — drives the badge colour: breaking = red,
 * feature = green, fix = blue (see `changelogTypeColor`).
 */
export type ChangelogType = 'breaking' | 'feature' | 'fix'

/**
 * A versioned changelog entry for one API (§2.7). Per-API registry data, loaded
 * from each API's `changelog.json` — same boundary as `ErrorRefEntry`. The
 * consuming page already knows which API is selected, so entries carry no
 * `apiId`/`apiName`. Authored newest-first.
 */
export interface ChangelogEntry {
  id: string
  /** Semver tag, e.g. "2.1.0". */
  version: string
  /** ISO date, YYYY-MM-DD. */
  date: string
  type: ChangelogType
  title: string
  description: string
}

/**
 * Tier-2 cross-API search hit: which API contains the keyword. Deliberately
 * id-agnostic — endpoint anchor ids are a frontend concern (generated by the
 * spec parser), so the DAL never returns them. The frontend resolves the exact
 * matching endpoints against its cached parse (see `useGlobalSearch`).
 */
export interface ApiSearchHit {
  apiId: string
  apiName: string
}

/** Environment a key is scoped to (§2.4). */
export type ApiKeyEnvironment = 'sandbox' | 'production'

/** Lifecycle status. Revoked keys are kept (greyed) for an audit trail. */
export type ApiKeyStatus = 'active' | 'revoked'

/**
 * A managed API key as the app sees it. Deliberately carries no plaintext
 * secret — only a `maskedKey` (prefix + last-4), mirroring real backends that
 * store a hash and can never re-reveal the secret. The full secret exists only
 * on the `CreatedApiKey` returned once at creation time.
 */
export interface ApiKey {
  id: string
  name: string
  environment: ApiKeyEnvironment
  /** e.g. "sk_sandbox_••••••••3f9a" — never the full secret. */
  maskedKey: string
  /** ISO timestamp. */
  createdAt: string
  /** ISO timestamp, or null when the key has never been used. */
  lastUsedAt: string | null
  /** ISO timestamp, or null when the key never expires. */
  expiresAt: string | null
  status: ApiKeyStatus
}

/** Fields the user supplies when creating a key. */
export interface CreateApiKeyInput {
  name: string
  environment: ApiKeyEnvironment
  /** ISO date, or null/omitted for no expiry. */
  expiresAt?: string | null
}

/**
 * Returned exactly once from `createKey`. Extends `ApiKey` with the plaintext
 * `secret`, which is shown to the user a single time and never persisted.
 */
export interface CreatedApiKey extends ApiKey {
  secret: string
}

/** Reporting window for usage analytics (§2.5). */
export type UsageWindow = '7d' | '30d'

/** Aggregate metrics for a key over a window. */
export interface UsageSummary {
  totalCalls: number
  errors4xx: number
  errors5xx: number
  /** (errors4xx + errors5xx) / totalCalls, in the range 0..1. */
  errorRate: number
  avgLatencyMs: number
}

/** One day of the time-series. */
export interface UsageTimePoint {
  /** ISO date, `YYYY-MM-DD`. */
  date: string
  calls: number
  errors: number
  avgLatencyMs: number
}

/** Per-endpoint breakdown row. */
export interface EndpointUsage {
  /** HTTP method, e.g. "GET". */
  method: string
  path: string
  calls: number
  /** 0..1. */
  errorRate: number
  avgLatencyMs: number
}

/**
 * Usage analytics for a single key over a window (§2.5). Mocked behind the DAL
 * today; a REST adapter would return the same shape from a metrics backend.
 */
export interface UsageReport {
  keyId: string
  window: UsageWindow
  summary: UsageSummary
  /** One point per day — 7 or 30 entries depending on the window. */
  series: UsageTimePoint[]
  endpoints: EndpointUsage[]
}

/** Per-API health indicator (§2.6). */
export type ApiHealth = 'operational' | 'degraded' | 'outage'

/** Lifecycle of an incident in the history feed. */
export type IncidentStatus = 'active' | 'resolved'

/** One timeline entry within an incident (newest first in the feed). */
export interface IncidentUpdate {
  /** e.g. "Investigating" | "Identified" | "Monitoring" | "Resolved". */
  status: string
  body: string
  /** ISO timestamp of this update. */
  timestamp: string
}

/** One incident in an API's history feed (§2.6). */
export interface StatusIncident {
  id: string
  title: string
  /** Severity — drives the API's health while the incident is active. */
  impact: Exclude<ApiHealth, 'operational'>
  status: IncidentStatus
  /** ISO timestamp the incident began. */
  startedAt: string
  /** ISO timestamp it was resolved, or null while still active. */
  resolvedAt: string | null
  /** Status updates, newest first — drives the incident timeline display. */
  updates: IncidentUpdate[]
}

/** One day of uptime in the 90-day window. */
export interface UptimeDay {
  /** ISO date, `YYYY-MM-DD`. */
  date: string
  /** Fraction of the day the API was up, 0..1. */
  uptime: number
}

/**
 * Per-API status (§2.6). Global infra health — NOT user-scoped. Mocked behind
 * the DAL today; a REST adapter would return the same shape from a status API.
 */
export interface ApiStatus {
  apiId: string
  apiName: string
  /** Derived: worst active incident's impact, else operational. */
  health: ApiHealth
  /** Mean uptime across the 90-day window, 0..1. */
  uptime90d: number
  /** One point per day — 90 entries, oldest first. */
  days: UptimeDay[]
  /** Incident history feed, newest first. */
  incidents: StatusIncident[]
}

/** Severity of a site-wide banner message. */
export type StatusBannerLevel = 'info' | 'degraded' | 'outage'

/**
 * A site-wide banner message (§2.6). Sourced independently of any single API's
 * status — it can carry anything (a general announcement, or a notice that an
 * API is degraded/down). `apiId` deep-links to that API's status page when set.
 */
export interface StatusBannerMessage {
  id: string
  level: StatusBannerLevel
  message: string
  apiId?: string
}
